name = "pixel_code_back"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-04-09"

main = "src/index.ts"

[vars]
FIREBASE_AUTH_DOMAIN = "pixel-code-dev.firebaseapp.com"
FIREBASE_DATABASE_URL = "https://pixel-code-dev.firebaseio.com"
FIREBASE_PROJECT_ID = "pixel-code-dev"
FIREBASE_STORAGE_BUCKET = "pixel-code-dev.appspot.com"
FIREBASE_MESSAGING_SENDER_ID = "943458328270"
FIREBASE_APP_ID = "1:943458328270:web:c56ed512e5fd6cb4b97a9f"
FIREBASE_MEASUREMENT_ID = "G-9VVK5LBK9S"